services:

  # Client node.
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: aleph
    networks:
      - private_net
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--login-server=https://hs.${PUBLIC_DOMAIN}:443 --accept-routes
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ./data/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped

  internal_proxy:
    image: traefik
    container_name: internal_proxy
    restart: unless-stopped
    network_mode: service:tailscale
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.constraints=Label(`traefik.scope`, `private`)"
      - "--providers.docker.network=private_net"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=duckdns"
      - "--certificatesresolvers.letsencrypt.acme.email=mail@mail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.disablePropagationCheck=true"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certResolver=letsencrypt"
      - "--entrypoints.websecure.http.tls.domains[0].main=${CONTROL_DOMAIN}"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.${CONTROL_DOMAIN}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik_internal/letsencrypt:/letsencrypt
    depends_on:
      - tailscale
    environment:
      DUCKDNS_TOKEN: "${DUCKDNS_TOKEN}"

  authelia_redis:
    image: redis
    restart: unless-stopped
    container_name: authelia_redis
    networks:
      - private_net

  authelia_generate_secrets:
    build: generate_secrets
    volumes:
      - ./data/authelia/secrets:/secrets

  authelia:
    image: authelia/authelia
    container_name: authelia
    restart: unless-stopped
    networks:
      - private_net
    labels:
      - "traefik.enable=true"
      - "traefik.scope=private"
      - "traefik.http.routers.authelia.rule=Host(`auth.${CONTROL_DOMAIN}`)"
      - "traefik.http.routers.authelia.entryPoints=websecure"
      - "traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/authz/forward-auth"
      - "traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Email,Remote-Name"
    depends_on:
      authelia_generate_secrets:
        condition: service_completed_successfully
      tailscale:
        condition: service_started
    volumes:
      - ./data/authelia:/config
    environment:
      TZ: America/Chicago
      X_AUTHELIA_CONFIG_FILTERS: template
      CONTROL_DOMAIN: ${CONTROL_DOMAIN}
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: /config/secrets/JWT_SECRET
      AUTHELIA_SESSION_SECRET_FILE: /config/secrets/SESSION_SECRET
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /config/secrets/STORAGE_ENCRYPTION_KEY

  syncthing:
    container_name: syncthing
    image: linuxserver/syncthing:latest
    restart: unless-stopped
    networks:
      - private_net
    labels:
      - "traefik.enable=true"
      - "traefik.scope=private"
      - "traefik.http.routers.syncthing.rule=Host(`syncthing.${CONTROL_DOMAIN}`)"
      - "traefik.http.routers.syncthing.entrypoints=websecure"
      - "traefik.http.routers.syncthing.middlewares=authelia@docker"
    environment:
      TZ: America/Chicago
      PUID: 1000
      PGID: 1000
    volumes:
      - ./data/syncthing:/config
      - /mnt/media/ark:/data1

  nextcloud_db:
    container_name: nextcloud_db
    image: postgres:16-alpine
    restart: unless-stopped
    networks:
      - private_net
    environment:
      POSTGRES_USER: nextcloud
      POSTGRES_DB: nextcloud
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/nextcloud_db:/var/lib/postgresql/data

  nextcloud_redis:
    container_name: nextcloud_redis
    image: redis:alpine
    restart: unless-stopped
    networks:
      - private_net
    volumes:
      - ./data/nextcloud_redis:/data

  nextcloud:
    container_name: nextcloud
    image: nextcloud:latest
    restart: unless-stopped
    networks:
      - private_net
    labels:
      - "traefik.enable=true"
      - "traefik.scope=private"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.${CONTROL_DOMAIN}`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.routers.nextcloud.tls=true"
    environment:
      TZ: "America/Chicago"
      POSTGRES_HOST: nextcloud_db
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: nextcloud_redis
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER:-nshan651}
      NEXTCLOUD_ADMIN_PASSWORD: ${DB_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: nextcloud.${CONTROL_DOMAIN}
      NC_skeletondirectory: ""
      OVERWRITEPROTOCOL: https
      OVERWRITEHOST: nextcloud.${CONTROL_DOMAIN}
      TRUSTED_PROXIES: traefik
    volumes:
      - ./data/nextcloud:/var/www/html
      - /mnt/media/vault/pix:/pix:ro
      - ./hooks/nextcloud-postinstall.sh:/docker-entrypoint-hooks.d/post-installation/nextcloud-postinstall.sh:ro
    depends_on:
      - nextcloud_db
      - nextcloud_redis

  # Connect using this url: `http://rss.aleph.arpa/api/greader.php`
  freshrss:
    image: linuxserver/freshrss:latest
    container_name: freshrss
    restart: unless-stopped
    networks:
      - private_net
    labels:
      - "traefik.enable=true"
      - "traefik.scope=private"
      - "traefik.http.routers.freshrss.rule=host(`rss.${CONTROL_DOMAIN}`)"
      - "traefik.http.routers.freshrss.entrypoints=websecure"
      - "traefik.http.routers.freshrss.middlewares=authelia@docker"
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "America/Chicago"
    volumes:
      - ./config/freshrss:/config

  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    networks:
      - private_net
    environment:
      TZ: "America/Chicago"
    volumes:
      - ./data/jellyfin:/config
      - /mnt/media/dox/movies:/movies
      - /mnt/media/dox/tv:/tv
      - /mnt/media/dox/music:/music
    labels:
      - "traefik.enable=true"
      - "traefik.scope=private"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${CONTROL_DOMAIN}`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.middlewares=authelia@docker"

  actual:
    image: actualbudget/actual-server:latest
    container_name: actual
    networks:
      - private_net
    volumes:
      - ./data/actual:/data
      - /mnt/media/vault/personal-finance/data:/budget
    environment:
      userFiles: "/budget"
    labels:
      - "traefik.enable=true"
      - "traefik.scope=private"
      - "traefik.http.routers.actual.rule=Host(`actual.${CONTROL_DOMAIN}`)"
      - "traefik.http.routers.actual.entrypoints=websecure"
      - "traefik.http.routers.actual.middlewares=authelia@docker"

networks:
  private_net:
    driver: bridge
