---
services:

  # Client node.
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: multivac
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--login-server=https://${CONTROL_DOMAIN}:443 --accept-routes
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ./data/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped

  internal_proxy:
    image: traefik
    container_name: internal_proxy
    restart: unless-stopped
    network_mode: service:tailscale
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # - "--providers.docker.network=services"
      - "--entrypoints.web.address=:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - tailscale

  syncthing:
    container_name: syncthing
    image: linuxserver/syncthing:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing.rule=Host(`syncthing.${TAILNET_DOMAIN}`)"
      - "traefik.http.routers.syncthing.entrypoints=web"
    environment:
      TZ: America/Chicago
      PUID: 1000
      PGID: 1000
    volumes:
      - ./config/syncthing:/config
      - /mnt/media/ark:/data1

  nextcloud_db:
    container_name: nextcloud_db
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: nextcloud
      POSTGRES_DB: nextcloud
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/nextcloud_db:/var/lib/postgresql/data

  nextcloud_redis:
    container_name: nextcloud_redis
    image: redis:alpine
    restart: unless-stopped

  nextcloud:
    container_name: nextcloud
    image: nextcloud:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.${TAILNET_DOMAIN}`)"
      - "traefik.http.routers.nextcloud.entrypoints=web"
    environment:
      TZ: "America/Chicago"
      POSTGRES_HOST: nextcloud_db
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: nextcloud_redis
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER:-nshan651}
      NEXTCLOUD_ADMIN_PASSWORD: ${DB_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: nextcloud.${TAILNET_DOMAIN}
      NC_skeletondirectory: ""
    volumes:
      - ./config/nextcloud:/config
      - ./data/nextcloud:/data
      - /mnt/media/vault/pix:/pix:ro # External dir I want to use
      - ./hooks/nextcloud-postinstall.sh:/docker-entrypoint-hooks.d/post-installation/nextcloud-postinstall.sh:ro
      # - /mnt/media/vault/pix:/data/nshan651/files/Photos:ro
    depends_on:
      - nextcloud_db
      - nextcloud_redis

  # Connect using this url: 'http://rss.multivac.arpa/api/greader.php'
  freshrss:
    image: linuxserver/freshrss:latest
    container_name: freshrss
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.freshrss.rule=host(`rss.${TAILNET_DOMAIN}`)'
      - 'traefik.http.routers.freshrss.entrypoints=web'
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "America/Chicago"
    volumes:
      - ./config/freshrss:/config

  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    environment:
      TZ: "America/Chicago"
    volumes:
      - ./data/jellyfin:/config
      - /mnt/media/dox/movies:/movies
      - /mnt/media/dox/tv:/tv
      - /mnt/media/dox/music:/music
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${TAILNET_DOMAIN}`)"
      - "traefik.http.routers.jellyfin.entrypoints=web"
