# Use a minimal Alpine Linux image as the base
FROM alpine:latest

# Set the working directory
WORKDIR /home/cabin

# Install base dependencies
RUN apk --update --no-cache add \
    build-base \
    curl \
    gcc \
    git \
    musl-dev

# Create a new user
RUN locale-gen en_US.UTF-8 && \
    adduser --quiet --disabled-password --shell /bin/zsh --home /home/cabin --gecos "User" cabin && \
    echo "cabin:p@ssword1" | chpasswd &&  usermod -aG sudo cabin

# Some basic development tools
RUN apk --update --no-cache add \
    zsh \
    bash \
    neovim \
    emacs \
    tmux \
    lf \
    ripgrep

# Install dwm for a cozy window manager environment
RUN git clone https:/github.com/nshan651/dwm.git && \
         cd dwm && \
         make && make install

# dwmblocks for useful status blocks
RUN git clone https://github.com/nshan651/dwmblocks.git \
         cd dwmblocks && \
         make && make install

# st is a nice and simple terminal emulator
RUN git clone https://github.com/nshan651/st.git \
         cd st && \
         make && make install

RUN apk --update --no-cache add \
    firefox \
    pcmanfm

# Install programming languages
RUN apk --update --no-cache add \
    python \
    sbcl \
    rust

# Custom configuration
RUN git clone https://github.com/nshan651/dotfiles.git

# Clean up package cache to reduce image size
RUN rm -rf /var/cache/apk/*

# Remove dotfiles
# TODO

# Entry point
CMD ["/bin/zsh"]
